CREATE DATABASE QuanLySinhVien;
USE QuanLySinhVien;

CREATE TABLE SINHVIEN (
	HOSV NVARCHAR(50),
	TENSV NVARCHAR(50),
	MASV NVARCHAR(20),
	NGAYSINH DATE,
	PHAI BIT,
	MAKHOA NVARCHAR(50)
)
CREATE TABLE KHOA(
	MAKHOA NVARCHAR(50),
	TENKHOA NVARCHAR(50)
)

CREATE TABLE MONHOC (
	TENMH NVARCHAR(50),
	MAMH NVARCHAR(50),
	SOTIET	INT
)

CREATE TABLE KETQUA (
	MASV NVARCHAR(20),
	MAMH NVARCHAR(50),
	LANTHI INT,
	DIEM FLOAT
)